ALTER TABLE app_users ADD COLUMN IF NOT EXISTS email VARCHAR(180);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS status VARCHAR(40) DEFAULT 'Active';
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS department VARCHAR(80);
