/** Manager UI entry for shared API — re-exports from app services. */
export {
  assignTicketToMe,
  getAgentCapacities,
  getAllTickets,
  getFilteredTickets,
  getManagerDashboard,
  getManagerReports,
  getTicketById,
  transferAllTickets,
  updateAgentLimit,
  updateTicket,
  addComment,
  getAttachments,
  downloadAttachment,
  deleteAttachment,
  uploadAttachment,
  exportReportCsv,
  getActiveProducts,
  getTeams,
  getTeamById,
  createTeam,
  updateTeam,
  deleteTeam,
  addTeamMember,
  removeTeamMember,
  addTeamProduct,
  removeTeamProduct,
} from "../../../../services/api";

export {
  buildExpectedProjection,
  executeTicketAction,
  getDestrovaApiErrorMessage,
  ProjectionTimeoutError,
  statusToAction,
  waitForTicketProjection,
} from "../../shared/api/ticketActions";
