export const STATUS_FLOW = {
  NEW: ["IN_PROGRESS"],
  IN_PROGRESS: ["WAITING_FOR_CUSTOMER", "RESOLVED"],
  WAITING_FOR_CUSTOMER: ["IN_PROGRESS"],
  RESOLVED: ["IN_PROGRESS", "CLOSED"],
  CLOSED: [],
};

export const CLOSURE_REASONS = [
  "SOLVED",
  "CUSTOMER_APPROVED",
  "INVALID",
  "NO_RESPONSE",
  "DUPLICATE",
];

